CREATE TABLE ADMIN_ENTITY (
  email VARCHAR(30) PRIMARY KEY,
  u_password VARCHAR(30) NOT NULL,
  u_role VARCHAR(10) NOT NULL CHECK (u_role IN ('Student', 'Teacher', 'Admin')),
  u_name VARCHAR(30) NOT NULL,
  FOREIGN KEY (email) REFERENCES USER_ENTITY(email) ON DELETE CASCADE
);