CREATE TRIGGER ADMIN_BEFORE_INSERT 
BEFORE INSERT ON ADMIN
FOR EACH ROW 
BEGIN 
  INSERT INTO USER VALUES (NEW.email, NEW.u_password, NEW.u_role, NEW.u_name);
END;

CREATE TRIGGER ADMIN_AFTER_DELETE
AFTER DELETE ON ADMIN 
FOR EACH ROW 
BEGIN 
  DELETE FROM USER 
  WHERE USER.email = OLD.email;
END;