SET @STUDENT_RATE = 0.02;
SET @STUDENT_TOTAL_DAYS = 7;
SET @TEACHER_RATE = 0.025;
SET @TEACHER_TOTAL_DAYS = 14;
SET @CURRENT_DAY = CURDATE() + 0;
SET @DATABASE = 'LIBRARY_MANAGEMENT';
SET @ACCUMULATE_DAY = @CURRENT_DAY + 2;