CREATE TRIGGER STUDENT_BEFORE_INSERT 
BEFORE INSERT ON STUDENT
FOR EACH ROW 
BEGIN 
  INSERT INTO USER VALUES (NEW.email, NEW.u_password, NEW.u_role, NEW.u_name);
END;

CREATE TRIGGER STUDENT_AFTER_DELETE
AFTER DELETE ON STUDENT 
FOR EACH ROW 
BEGIN 
  DELETE FROM USER 
  WHERE USER.email = OLD.email;
END;