CREATE TABLE ENTRY_RELATION (
  id INT GENERATED BY DEFAULT ON NULL AS IDENTITY,  
  email VARCHAR(30) NOT NULL ,
  book_ID INT NOT NULL,
  b_category VARCHAR(30)  NOT NULL CHECK (b_category IN ('FICTION', 'NON-FICTION', 'MYSTERY', 'ROMANCE', 
  'THRILLER')),
  u_name VARCHAR(30),
  u_role VARCHAR(10) NOT NULL CHECK (u_role IN ('Student', 'Teacher', 'Admin')),
  title VARCHAR(30),
  fine_rate DECIMAL(18, 2),
  issue_day DATE,
  accumulate_day DATE,
  current_fine DECIMAL(18, 2),
  deadline DATE,
  e_status VARCHAR(10) DEFAULT 'In Borrow',
  FOREIGN KEY (email) REFERENCES USER_ENTITY(email),
  FOREIGN KEY (book_ID) REFERENCES BOOK_ENTITY(ID),
  CHECK (u_role != 'ADMIN'),
  CHECK (current_fine <= 0),
  CONSTRAINT ENTRY_RELATION_CON CHECK (e_status IN ('In Borrow', 'Late'))
);

