CREATE TRIGGER TEACHER_BEFORE_INSERT 
BEFORE INSERT ON TEACHER
FOR EACH ROW 
BEGIN 
  INSERT INTO USER VALUES (NEW.email, NEW.u_password, NEW.u_role, NEW.u_name);
END;

CREATE TRIGGER TEACHER_AFTER_DELETE
AFTER DELETE ON TEACHER 
FOR EACH ROW 
BEGIN 
  DELETE FROM USER 
  WHERE USER.email = OLD.email;
END;