INSERT INTO BOOK 
VALUES (NULL, 'Book1', 'Author1', 'FICTION', NULL, NULL, NULL, NULL, 'Available');
INSERT INTO BOOK 
VALUES (NULL, 'Book2', 'Author2', 'NON-FICTION', NULL, NULL, NULL, NULL, 'Available');
INSERT INTO BOOK 
VALUES (NULL, 'Book3', 'Author3', 'MYSTERY', NULL, NULL, NULL, NULL, 'Available');
INSERT INTO BOOK 
VALUES (NULL, 'Book4', 'Author4', 'ROMANCE', NULL, NULL, NULL, NULL, 'Available');
INSERT INTO BOOK 
VALUES (NULL, 'Book1', 'Author1', 'ROMANCE', NULL, NULL, NULL, NULL, 'Available');

