INSERT INTO BOOK 
VALUES (1, 'Book1', 'Author1', 'FICTION');
INSERT INTO BOOK 
VALUES (2, 'Book2', 'Author2', 'NON-FICTION');
INSERT INTO BOOK 
VALUES (3, 'Book3', 'Author3', 'MYSTERY');
INSERT INTO BOOK 
VALUES (4, 'Book4', 'Author4', 'ROMANCE');

SELECT * FROM BOOK;