CREATE TRIGGER BOOK_AFTER_INSERT
AFTER INSERT ON BOOK
FOR EACH ROW
BEGIN
  INSERT INTO STOCK VALUES (NEW.ID, NEW.title, NEW.num_stock);
  UPDATE STOCK 
  SET num_stock = (SELECT COUNT(title) FROM BOOK WHERE BOOK.title = NEW.title)
  WHERE title = NEW.title;
END;

CREATE TRIGGER BOOK_AFTER_DELETE_HANDLE_CASE1
AFTER DELETE ON BOOK
FOR EACH ROW
BEGIN
  DELETE FROM STOCK WHERE STOCK.num_stock = 1 AND STOCK.book_ID = OLD.ID;
  UPDATE STOCK 
  SET num_stock = (SELECT COUNT(title) FROM BOOK WHERE BOOK.title = OLD.title)
  WHERE title = OLD.title;
END;

CREATE TRIGGER BOOK_AFTER_DELETE_HANDLE_CASE2
AFTER DELETE ON BOOK
FOR EACH ROW
BEGIN
  UPDATE STOCK 
  SET num_stock = (SELECT COUNT(title) FROM BOOK WHERE BOOK.title = OLD.title)
  WHERE title = OLD.title;
  DELETE FROM STOCK WHERE STOCK.num_stock = 1 AND STOCK.book_ID = OLD.ID;
END;

DROP TRIGGER BOOK_AFTER_DELETE;


